"""Configuration and translations with optimized caching."""

from functools import lru_cache

# Translations dictionary
TRANSLATIONS = {
    "en": {
        # feedback
        "feedback_title": "Feedback",
        "feedback_desc": "Share your thoughts and suggestions with us.",
        "feedback_enter_text": "Please write feedback.",
        "feedback_min_length": "Minimum 10 characters required.",
        "feedback_submitted": "Feedback submitted!",
        "feedback_server_error": "Server error",
        # main nav/services
        "dashboard": "Dashboard",
        "weather": "Weather Forecast",
        "market": "Market Prices",
        "crop": "Crop Advisory",
        "schemes": "Government Schemes",
        "logout": "Logout",
        "app_name": "Farmer Assistant",

        # index page
        "welcome_to": "Welcome to",
        "portal_name": "My Agriculture Portal",
        "redirecting": "Redirecting you to your dashboard...",
        "if_not_redirected": "If you are not redirected automatically,",
        "click_here": "click here",

        # login/register pages
        "login_title": "Farmer Assistant Login",
        "register_title": "Register",
        "register_header": "User Registration",
        "name_label": "Name",
        "mobile_label": "Mobile Number",
        "username_label": "Username",
        "password_label": "Password",
        "enter_name": "Enter your name",
        "enter_mobile": "Enter mobile number",
        "enter_password": "Enter password",
        "mobile_invalid": "Mobile number must be exactly 10 digits",
        "password_invalid": "Password must be at least 6 characters",
        "login_button": "Login",
        "admin_login_button": "Login",
        "register_button": "Register",
        "already_have_account": "Already have an account?",
        "login_link": "Login",
        "no_account": "Don't have an account?",
        "register_link": "Register",
        "invalid_credentials": "Invalid Credentials",
        "mobile_exists": "A user with that mobile number already exists",
        "forgot_password_link": "Forgot Password?",
        "forgot_password_title": "Forgot Password",
        "forgot_password_header": "Reset Your Password",
        "forgot_mobile_label": "Mobile Number",
        "forgot_password_label": "New Password",
        "reset_button": "Reset Password",
        "user_not_found": "No user found with that mobile number",
        "password_reset_success": "Password has been reset successfully",
        "registration_success": "Registration successful, please log in",
        "enter_otp": "Enter OTP",
        "new_password_label": "New Password",
        "submit": "Submit",
        "otp_incorrect": "Incorrect OTP, please try again",
        "otp_title_reg": "Verify Registration",
        "otp_reg_msg": "An OTP has been sent to your mobile. Enter it below to complete registration.",
        "otp_sent": "OTP has been sent to your mobile",
        "otp_title_forgot": "Verify Reset",
        "otp_forgot_msg": "Enter the OTP you received and choose a new password.",

        # crop page
        "select_criteria": "Select Your Criteria",
        "season_label": "Season",
        "soil_label": "Soil Type",
        "choose_season": "-- Choose Season --",
        "choose_soil": "-- Choose Soil Type --",
        "results_title": "Recommended Crops",
        "fertilizer": "Fertilizer",
        "pest_control": "Pest Control",
        "no_crops_found": "No crops found for the selected criteria.",
        "try_different": "Try a different combination of season and soil type",
        "back_to_dashboard": "Back to Dashboard",
        "open": "Open",
        "crop_desc": "Get personalized crop recommendations based on your soil type and season. Expert farming tips included.",
        "weather_desc": "Check real-time weather conditions and detailed forecasts to plan your farming activities.",
        "market_desc": "View latest crop market prices and trends to make informed decisions for selling.",
        "schemes_desc": "Explore available government schemes and programs for farmers.",

        # weather page
        "weather_title": "Weather",
        "weather_subtitle": "Check conditions for your area",
        "city_label": "City",
        "city_placeholder": "Search a city...",
        "get_weather": "Get Weather",
        "back": "Back",
        "humidity": "Humidity",
        "feels_like": "Feels Like",
        "city_not_found": "City not found",
        "not_found_header": "Not Found",
        "not_found_desc": "We couldn't find weather data for this city. Please try another location.",
        "no_data_yet": "No data yet",
        "enter_city_to_start": "Enter a city name to get started",

        # market page
        "select_crop": "Select Crop",
        "see_prices": "See Prices",
        "choose_crop": "-- Choose a Crop --",
        "price_history": "Price History",
        "date_label": "Date",
        "price_label": "Price",
        "market_insights": "Market Insights",
        "market_trend": "Market Trend",
        "recommendation": "Recommendation",
        "no_price_data": "No price data available for selected crop",
        "track_prices": "Track crop prices and make informed selling decisions",
        "find_crop_prices": "Find Crop Prices",

        # schemes page
        "scheme_label": "Scheme",
        "description_label": "Description",
        "link_label": "Official Link",
        "apply": "Apply",
        "nodata": "No schemes available at the moment.",

        # profile page
        "profile_title": "Profile",
        "update_profile": "Update Profile",
        "update_button": "Update",
        "update_success": "Profile updated successfully",
        "delete_account": "Delete Account",
        "account_deleted": "Your account has been deleted.",
        "activity_title": "Recent Activity",
        "no_activity": "No recorded activity yet.",
        "select_state": "Select State",
        "select_district": "Select District",
        "select_village": "Select Village",
        "welcome_user": "Welcome",
        "dashboard_tagline": "Your personal farming companion - Choose a service below",
        "all_fields_required": "All fields required",
        "name_mobile_required": "Name and Mobile are required",
        "crop_page_error": "Crop page error. Check terminal.",
        "login_required_alert": "Please log in to continue",
        "error_header": "Oops! Something went wrong",
        "error_default": "An unexpected error occurred",
        "back_to_home": "Back to Home",
        "feedback_title": "Feedback",
        "feedback_desc": "Share your thoughts and suggestions with us.",
        "feedback_enter_text": "Please write feedback.",
        "feedback_min_length": "Minimum 10 characters required.",
        "feedback_submitted": "Feedback submitted!",
        "feedback_server_error": "Server error",
        "manage_market_prices": "Manage Market Prices",
        "admin_panel_market": "Administrator panel for market price updates",
        "update_market_prices": "Update Market Prices",
        "price_input_placeholder": "Enter price in rupees",
        "current_market_prices": "Current Market Prices",
        "crop_name_label": "Crop Name",
        "current_price_label": "Current Price (₹/Quintal)",
        "last_updated_label": "Last Updated",
        "no_data_label": "No data",
        "registered_farmers": "Registered Farmers",
        "no_registered_farmers": "No registered farmers yet.",
        "user_feedback": "User Feedback",
        "no_feedback_available": "No feedback available.",
        "delete_feedback_confirm": "Delete this feedback?",
        "back_to_admin_dashboard": "Back to Dashboard",
        # admin-related
        "admin_login_required": "Administrator login required",
        "admin_dashboard": "Admin Dashboard",
        "administrator_login": "Administrator Login",
        "view_feedback": "View User Feedback",
        "manage_market_prices": "Manage Market Prices",

        "crop_advisory_title": "Crop Advisory System",
        "subtitle": "Find best crops for your land",

        "kharif": "Kharif",
        "rabi": "Rabi",
        "zaid": "Zaid",

        "black_soil": "Black Soil",
        "loamy_soil": "Loamy Soil",
        "clay_soil": "Clay Soil",

        "get_recommendations": "Get Recommendations",
        "select_criteria": "Select Criteria",
        "choose_season": "Choose Season",
        "choose_soil": "Choose Soil",

        "fertilizer": "Fertilizer",
        "pest_control": "Pest Control",

        "no_crops_found": "No crops found",
        "try_different": "Try different options"
    },

    "mr": {

        "feedback_title": "अभिप्राय",
        "feedback_desc": "आपले विचार आणि सूचना आमच्याशी शेअर करा.",
        "feedback_enter_text": "कृपया अभिप्राय लिखें.",
        "feedback_min_length": "किमान 10 अक्षर आवश्यक हैं.",
        "feedback_submitted": "अभिप्राय सबमिट किया गया!",
        "feedback_server_error": "सर्वर त्रुटि",

        "dashboard": "डॅशबोर्ड",
        "weather": "हवामान अंदाज",
        "market": "बाजारभाव",
        "crop": "पिक सल्ला",
        "schemes": "शासकीय योजना",
        "logout": "लॉगआउट",
        "app_name": "शेतकरी सहाय्यक",

         "welcome_to": "स्वागत आहे",
        "portal_name": "माझे कृषी पोर्टल",
        "redirecting": "तुम्हाला डॅशबोर्डवर पाठवले जात आहे...",
        "if_not_redirected": "जर आपोआप रीडायरेक्ट झाले नाही तर,",
        "click_here": "इथे क्लिक करा",

        "login_title": "शेतकरी सहाय्यक लॉगिन",
        "register_title": "नोंदणी",
        "register_header": "वापरकर्ता नोंदणी",
        "name_label": "नाव",
        "mobile_label": "मोबाइल क्रमांक",
        "username_label": "वापरकर्तानाव",
        "password_label": "पासवर्ड",
        "enter_name": "आपले नाव टाका",
        "enter_mobile": "मोबाइल क्रमांक टाका",
        "enter_password": "पासवर्ड टाका",
        "mobile_invalid": "मोबाइल क्रमांक 10 अंकांचा असावा",
        "password_invalid": "पासवर्ड किमान 6 अक्षरांचा असावा",
        "login_button": "लॉगिन",
        "register_button": "नोंदणी करा",
        "already_have_account": "आधीच खाते आहे?",
        "login_link": "लॉगिन करा",
        "no_account": "खाते नाही?",
        "register_link": "नोंदणी करा",
        "invalid_credentials": "चुकीची माहिती",
        "mobile_exists": "या मोबाइल क्रमांकावर आधीच वापरकर्ता आहे",
        "forgot_password_link": "पासवर्ड विसरलात?",
        "forgot_password_title": "पासवर्ड रीसेट",
        "forgot_password_header": "आपला पासवर्ड बदला",
        "forgot_mobile_label": "मोबाइल क्रमांक",
        "forgot_password_label": "नवीन पासवर्ड",
        "reset_button": "रीसेट करा",
        "user_not_found": "या मोबाइल क्रमांकावर वापरकर्ता सापडला नाही",
        "password_reset_success": "पासवर्ड यशस्वीरित्या बदलला",
        "registration_success": "नोंदणी यशस्वी, कृपया लॉगिन करा",
        "enter_otp": "OTP टाका",
        "new_password_label": "नवीन पासवर्ड",
        "submit": "सबमिट करा",
        "otp_incorrect": "चुकीचा OTP, पुन्हा प्रयत्न करा",

        "select_criteria": "निकष निवडा",
        "season_label": "हंगाम",
        "soil_label": "मातीचा प्रकार",
        "choose_season": "-- हंगाम निवडा --",
        "choose_soil": "-- माती निवडा --",
        "results_title": "शिफारस केलेली पिके",
        "fertilizer": "खत",
        "pest_control": "किड नियंत्रण",
        "no_crops_found": "निवडलेल्या निकषांसाठी पिके सापडली नाहीत",
        "try_different": "वेगळा पर्याय वापरून पाहा",
        "back_to_dashboard": "डॅशबोर्डवर परत जा",

        "crop_advisory_title": "पीक सल्ला प्रणाली",
        "subtitle": "तुमच्या जमिनीसाठी योग्य पीक निवडा",

        "kharif": "खरीप",
        "rabi": "रब्बी",
        "zaid": "झायड",

        "black_soil": "काळी माती",
        "loamy_soil": "दोमट माती",
        "clay_soil": "चिकण माती",

        "get_recommendations": "सल्ला मिळवा",
        "select_criteria": "निकष निवडा",
        "choose_season": "हंगाम निवडा",
        "choose_soil": "माती निवडा",

        "fertilizer": "खत",
        "pest_control": "कीड नियंत्रण",

        "no_crops_found": "कोणतेही पीक सापडले नाही",
        "try_different": "इतर पर्याय वापरा",

        "weather_title": "हवामान",
        "weather_subtitle": "आपल्या भागाचे हवामान तपासा",
        "city_label": "शहर",
        "city_placeholder": "शहर शोधा...",
        "get_weather": "हवामान पाहा",
        "back": "मागे",
        "humidity": "आर्द्रता",
        "feels_like": "जाणवणारे तापमान",
        "city_not_found": "शहर सापडले नाही",
        "no_data_yet": "अजून माहिती नाही",
        "enter_city_to_start": "शहराचे नाव टाका",

        "select_crop": "पीक निवडा",
        "see_prices": "भाव पहा",
        "choose_crop": "-- पीक निवडा --",
        "price_history": "भाव इतिहास",
        "date_label": "दिनांक",
        "price_label": "भाव",
        "market_insights": "बाजार विश्लेषण",
        "market_trend": "बाजार ट्रेंड",
        "recommendation": "सल्ला",
        "no_price_data": "या पिकासाठी भाव उपलब्ध नाही",
        "track_prices": "भाव ट्रॅक करा आणि योग्य निर्णय घ्या",

        "scheme_label": "योजना",
        "description_label": "वर्णन",
        "link_label": "अधिकृत लिंक",
        "apply": "अर्ज करा",
        "nodata": "सध्या कोणतीही योजना उपलब्ध नाही",

        "profile_title": "प्रोफाइल",
        "update_button": "अपडेट करा",
        "update_success": "प्रोफाइल अपडेट झाले",
        "delete_account": "खाते हटवा",

        "account_deleted": "आपले खाते हटवले गेले",
        "activity_title": "अलीकडील क्रिया",
        "no_activity": "अजून कोणतीही क्रिया नाही",

        "age_label": "वय",
        "farmer_type": "शेतकऱ्याचा प्रकार",
        "select_type": "प्रकार निवडा",
        "small_farmer": "लहान शेतकरी (≤2 हेक्टर)",
        "medium_farmer": "मध्यम शेतकरी (2-10 हेक्टर)",
        "large_farmer": "मोठा शेतकरी (>10 हेक्टर)",
        "marginal_farmer": "अतिसूक्ष्म शेतकरी (<1 हेक्टर)",

        "state_label": "राज्य",
        "district_label": "जिल्हा",
        "village_label": "गाव",
        "land_label": "जमीन (हेक्टर)",
        "select_state": "राज्य निवडा",

        "soil_type": "मातीचा प्रकार",
        "select_soil": "माती निवडा",

        "nearby_farmers": "जवळचे शेतकरी",
        "similar_interest": "तुमच्या जिल्ह्यातील शेतकरी",
        "land_hectare": "जमीन",

        "personalized_crops": "वैयक्तिक पिक शिफारसी",
        "based_on_data": "तुमच्या माहितीनुसार",
        "view_all": "सर्व पहा",

        "delete_confirm": "तुम्हाला खातं खरंच हटवायचं आहे का?",
        "delete_feedback_confirm": "हे फीडबॅक हटवायचे का?",

        "market": "बाजारभाव",
        "track_prices": "पिकांचे भाव पाहा आणि योग्य निर्णय घ्या",
        "back_to_dashboard": "डॅशबोर्डवर परत जा",

        "find_crop_prices": "पिकांचे भाव शोधा",
        "select_crop": "पीक निवडा",
        "choose_crop": "-- पीक निवडा --",
        "see_prices": "भाव पहा",

        "price_history": "भाव इतिहास",
        "date_label": "दिनांक",
        "price_label": "भाव",

        "market_insights": "बाजार विश्लेषण",
        "market_trend": "बाजाराचा कल",
        "recommendation": "सल्ला",

        "trend_upward": "वाढता",
        "trend_downward": "घटता",

        "suggestion_sell": "Good time to sell - prices trending upward",
        "suggestion_wait": "Consider waiting - prices trending downward",
        "suggestion_stable": "Stable prices - hold or sell based on your needs",

        "sell": "आता विक्री करा",
        "hold": "थांबा",
        "buy": "खरेदी करा",
          "Cotton": "कापूस",
    "Soybean": "सोयाबीन",
    "Tur": "तूर",

    "Rice": "तांदूळ",
    "Maize": "मका",
    "Groundnut": "शेंगदाणा",
    "Sugarcane": "ऊस",

    "Wheat": "गहू",
    "Gram": "हरभरा",
    "Sunflower": "सूर्यफूल",
    "Mustard": "मोहरी",
    "Barley": "जव",
    "Peas": "मटार",

    "Watermelon": "टरबूज",
    "Cucumber": "काकडी",
    "Muskmelon": "खरबूज",
    "Vegetables": "भाज्या",
    "Fodder crops": "चारा पिके"
    } ,

    "hi": {

        # feedback
        "feedback_title": "प्रतिक्रिया",
        "feedback_desc": "अपने विचार और सुझाव हमारे साथ साझा करें।",
        "feedback_enter_text": "कृपया प्रतिक्रिया लिखें।",
        "feedback_min_length": "कम से कम 10 अक्षर आवश्यक हैं।",
        "feedback_submitted": "प्रतिक्रिया सबमिट की गई!",
        "feedback_server_error": "सर्वर त्रुटि",
        # common
        "dashboard": "डैशबोर्ड",
        "weather": "मौसम पूर्वानुमान",
        "market": "बाजार भाव",
        "crop": "फसल सलाह",
        "schemes": "सरकारी योजनाएं",
        "logout": "लॉगआउट",
        "app_name": "किसान सहायक",

        # index page
        "welcome_to": "स्वागत है",
        "portal_name": "मेरा कृषि पोर्टल",
        "redirecting": "आपको डैशबोर्ड पर भेजा जा रहा है...",
        "if_not_redirected": "यदि आप स्वतः रीडायरेक्ट नहीं होते हैं,",
        "click_here": "यहाँ क्लिक करें",

        # login/register
        "login_title": "किसान सहायक लॉगिन",
        "register_title": "पंजीकरण",
        "register_header": "उपयोगकर्ता पंजीकरण",
        "name_label": "नाम",
        "mobile_label": "मोबाइल नंबर",
        "username_label": "यूज़रनेम",
        "password_label": "पासवर्ड",
        "enter_name": "अपना नाम दर्ज करें",
        "enter_mobile": "मोबाइल नंबर दर्ज करें",
        "enter_password": "पासवर्ड दर्ज करें",
        "mobile_invalid": "मोबाइल नंबर 10 अंकों का होना चाहिए",
        "password_invalid": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
        "login_button": "लॉगिन",
        "admin_login_button": "लॉगिन",
        "register_button": "पंजीकरण करें",
        "already_have_account": "क्या आपके पास पहले से खाता है?",
        "login_link": "लॉगिन करें",
        "no_account": "क्या आपके पास खाता नहीं है?",
        "register_link": "पंजीकरण करें",
        "invalid_credentials": "अमान्य जानकारी",
        "mobile_exists": "इस मोबाइल नंबर पर पहले से उपयोगकर्ता मौजूद है",
        "forgot_password_link": "पासवर्ड भूल गए?",
        "forgot_password_title": "पासवर्ड रीसेट",
        "forgot_password_header": "अपना पासवर्ड रीसेट करें",
        "forgot_mobile_label": "मोबाइल नंबर",
        "forgot_password_label": "नया पासवर्ड",
        "reset_button": "रीसेट करें",
        "user_not_found": "इस मोबाइल नंबर से कोई उपयोगकर्ता नहीं मिला",
        "password_reset_success": "पासवर्ड सफलतापूर्वक बदल दिया गया",
        "registration_success": "पंजीकरण सफल, कृपया लॉगिन करें",
        "enter_otp": "OTP दर्ज करें",
        "new_password_label": "नया पासवर्ड",
        "submit": "सबमिट करें",
        "otp_incorrect": "गलत OTP, कृपया पुनः प्रयास करें",
        "otp_title_reg": "पंजीकरण सत्यापन",
        "otp_reg_msg": "आपके मोबाइल पर OTP भेजा गया है। पंजीकरण पूरा करने के लिए दर्ज करें।",
        "otp_sent": "OTP आपके मोबाइल पर भेजा गया है",
        "otp_title_forgot": "रीसेट सत्यापन",
        "otp_forgot_msg": "प्राप्त OTP दर्ज करें और नया पासवर्ड चुनें।",

        # crop
        "select_criteria": "मानदंड चुनें",
        "season_label": "मौसम",
        "soil_label": "मिट्टी का प्रकार",
        "choose_season": "-- मौसम चुनें --",
        "choose_soil": "-- मिट्टी चुनें --",
        "results_title": "अनुशंसित फसलें",
        "fertilizer": "उर्वरक",
        "pest_control": "कीट नियंत्रण",
        "no_crops_found": "चयनित मानदंड के लिए कोई फसल नहीं मिली",
        "try_different": "कोई अन्य विकल्प आज़माएं",
        "back_to_dashboard": "डैशबोर्ड पर वापस जाएं",
        "open": "खोलें",
        "crop_desc": "मिट्टी और मौसम के आधार पर फसल की सिफारिश प्राप्त करें।",
        "weather_desc": "वास्तविक समय का मौसम और पूर्वानुमान देखें।",
        "market_desc": "नवीनतम बाजार भाव और रुझान देखें।",
        "schemes_desc": "किसानों के लिए सरकारी योजनाएं देखें।",

        # weather
        "weather_title": "मौसम",
        "weather_subtitle": "अपने क्षेत्र का मौसम देखें",
        "city_label": "शहर",
        "city_placeholder": "शहर खोजें...",
        "get_weather": "मौसम देखें",
        "back": "वापस",
        "humidity": "आर्द्रता",
        "feels_like": "महसूस होने वाला तापमान",
        "city_not_found": "शहर नहीं मिला",
        "not_found_header": "नहीं मिला",
        "not_found_desc": "इस शहर के लिए मौसम डेटा नहीं मिला",
        "no_data_yet": "अभी तक कोई डेटा नहीं",
        "enter_city_to_start": "शहर का नाम दर्ज करें",

        # market
        "select_crop": "फसल चुनें",
        "see_prices": "भाव देखें",
        "choose_crop": "-- फसल चुनें --",
        "price_history": "भाव इतिहास",
        "date_label": "तारीख",
        "price_label": "भाव",
        "market_insights": "बाजार विश्लेषण",
        "market_trend": "बाजार रुझान",
        "recommendation": "सिफारिश",
        "no_price_data": "इस फसल के लिए कोई डेटा उपलब्ध नहीं",
        "track_prices": "भाव ट्रैक करें और सही निर्णय लें",
        "find_crop_prices": "फसल के भाव खोजें",

        # schemes
        "scheme_label": "योजना",
        "description_label": "विवरण",
        "link_label": "आधिकारिक लिंक",
        "apply": "आवेदन करें",
        "nodata": "फिलहाल कोई योजना उपलब्ध नहीं है",

        # profile
        "profile_title": "प्रोफाइल",
        "update_button": "अपडेट करें",
        "update_success": "प्रोफाइल सफलतापूर्वक अपडेट हुआ",
        "delete_account": "खाता हटाएं",
        "account_deleted": "आपका खाता हटा दिया गया है",
        "activity_title": "हाल की गतिविधि",
        "no_activity": "अभी तक कोई गतिविधि नहीं",

        # admin
        "admin_login_required": "एडमिन लॉगिन आवश्यक है",
        "admin_dashboard": "एडमिन डैशबोर्ड",
        "administrator_login": "एडमिन लॉगिन",
        "view_feedback": "उपयोगकर्ता प्रतिक्रिया देखें",
        "manage_market_prices": "बाजार मूल्य प्रबंधित करें",

        "age_label": "आयु",
        "farmer_type": "किसान का प्रकार",
        "select_type": "प्रकार चुनें",
        "small_farmer": "छोटा किसान (≤2 हेक्टेयर)",
        "medium_farmer": "मध्यम किसान (2-10 हेक्टेयर)",
        "large_farmer": "बड़ा किसान (>10 हेक्टेयर)",
        "marginal_farmer": "सीमांत किसान (<1 हेक्टेयर)",

        "state_label": "राज्य",
        "district_label": "जिला",
        "village_label": "गांव",
        "land_label": "भूमि (हेक्टेयर)",
        "select_state": "राज्य चुनें",

        "nearby_farmers": "नजदीकी किसान",
        "similar_interest": "आपके जिले के किसान",
        "land_hectare": "भूमि",

        "personalized_crops": "व्यक्तिगत फसल सिफारिशें",
        "based_on_data": "आपकी जानकारी के आधार पर",
        "view_all": "सभी देखें",

        "delete_confirm": "क्या आप वाकई अपना खाता हटाना चाहते हैं?",
        "delete_feedback_confirm": "यह प्रतिक्रिया हटाएं?"
    }
}


@lru_cache(maxsize=3)
def get_text(lang="en"):
    """Get cached translations for language - O(1) lookup with English fallback."""
    base = TRANSLATIONS.get("en", {})
    locale = TRANSLATIONS.get(lang, {})
    # Ensure any missing keys in a locale use English as fallback
    merged = {**base, **locale}
    return merged


# Pre-compute supported languages
SUPPORTED_LANGS = {"en", "mr", "hi"}
